name: Release
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10'
      - name: Install Dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Debug Before Release
        run: |
          git status
          ls -la # 显示当前目录文件
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release --debug
      - name: Debug After Release
        run: |
          git status
          cat CHANGELOG.md || echo "CHANGELOG.md not found"
